import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "../providers/ThemeProvider";
import { Toaster } from "@/components/ui/sonner";
import { QueryProvider } from "../providers/QueryProvider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { DashboardSidebar } from "@/components/sidebar-02/app-sidebar";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Brova",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body className={`${inter.variable} antialiased `}>
        <Providers>
          <QueryProvider>
            <TooltipProvider>{children}</TooltipProvider>
          </QueryProvider>
          <Toaster richColors />
        </Providers>
      </body>
    </html>
  );
}
